services:
  deploy-agent:
    image: ghcr.io/devver-inc/deploy-agent:latest
    container_name: deploy-agent
    ports:
      - "3080:80"
    volumes:
      - devver-app:/app
      - devver-pm2:/root/.pm2
    environment:
      - DEVVER_SECRET=dev-secret-123
      - NODE_ENV=production
      - DEVVER_WIDGET_URL=https://cdn.jsdelivr.net/gh/Devver-Inc/overlay@main/public/devver-overlay.iife.js

volumes:
  devver-app:
  devver-pm2:
