services:
  deploy-agent:
    image: ghcr.io/devver-inc/deploy-agent:latest
    container_name: deploy-agent
    ports:
      - "3080:80"
    volumes:
      - devver-app:/app
      - devver-pm2:/root/.pm2
    environment:
      - DEVVER_SECRET
      - NODE_ENV
      - DEVVER_WIDGET_URL
      - DEVVER_MONGO_CONNECTION_STRING

volumes:
  devver-app:
  devver-pm2:
